#!/bin/bash

MESSAGE=$(cat $1)
REGEX="^(\[FIX\]|\[UPDATE\]|\[ADD\]|\[maven-release-plugin\]) .+"

if ! [[ $MESSAGE =~ $REGEX ]]; then
  echo "Your commit was rejected."
  echo "Please rename your commit to abide by the following naming conventions: [FIX] <commit message> or [UPDATE] <commit message> or [ADD] <commit message>"
  exit 1
fi