style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/EvgeniaPatsoni/TestRelease
options:
  commits:
    filters:
       Type:
         - feat
         - fix
         - build
         - chore
         - ci
         - doc
         - style
         - test
         - perf
         - refactor
  commit_groups:
    title_maps:
       feat: Features
       fix: Bug Fixes
       build: Build
       chore: Chores
       ci: Continuous Integration
       doc: Documentation
       style: Styles
       test: Tests
       perf: Performance Improvements
       refactor: Code Refactoring
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE